//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetworkNeighbors.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Referral
    {
        public int id { get; set; }
        public string referrer_voter_id { get; set; }
        public string referred_voter_id { get; set; }
        public int status_id { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual Voter Voter { get; set; }
        public virtual Voter Voter1 { get; set; }
    }
}
